### ISSUE TITLE
Playlist scroller planning

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/hyperamp#182]
We have a large table scroller now, but there are lots of things we can do to make it better.  For those interested it can be found here: https://github.com/hypermodules/hyperamp/tree/master/renderer/elements/table

## Bugs

- [x] Fix list highlights (https://github.com/hypermodules/hyperamp/issues/175)
- [ ] Only slice on odd or even so n-th child doesn't go out of order.

## Performance + Improvements

- [x] yo-yo-ify maybe (https://github.com/hypermodules/hyperamp/issues/174) or remove bel from render paths.
- [ ] [Fragment](https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment) node pooling
- [ ] Refactor into a module

## Other notes: 

- Nanomnorph Child re-order bug (https://github.com/yoshuawuyts/nanomorph/pull/71)
- [UITableViewDataSource](https://developer.apple.com/documentation/uikit/uitableviewdatasource) has a well developed API.  Might be able to pull some ideas from that.

**Comment by bcomnes** [comment]
This isn't a very functional issue.  Breaking it up into smaller issues.
